Controllers/CommentsController.cs
using BlogApp.Data;
using BlogApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BlogApp.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class CommentsController : Controller
    {
        private readonly BlogAppContext _context;

        public CommentsController(BlogAppContext context)
        {
            _context = context;
        }

        // GET: Comments
        public async Task<IActionResult> Index()
        {
            var blogAppContext = _context.Comments.Include(c => c.Post);
            return View(await blogAppContext.ToListAsync());
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Comments == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.Post)
                .FirstOrDefaultAsync(m => m.CommentID == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create
        public IActionResult Create()
        {
            ViewData["PostID"] = new SelectList(_context.Posts, "PostID", "PostID");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("CommentID,PostID,email,Content,CreatedDate,IsApproved")] Comment comment
        )
        {
            if (ModelState.IsValid)
            {
                _context.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PostID"] = new SelectList(_context.Posts, "PostID", "PostID", comment.PostID);
            return View(comment);
        }

        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Comments == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            ViewData["PostID"] = new SelectList(_context.Posts, "PostID", "PostID", comment.PostID);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            string id,
            [Bind("CommentID,PostID,email,Content,CreatedDate,IsApproved")] Comment comment
        )
        {
            if (id != comment.CommentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.CommentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PostID"] = new SelectList(_context.Posts, "PostID", "PostID", comment.PostID);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Comments == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.Post)
                .FirstOrDefaultAsync(m => m.CommentID == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Comments == null)
            {
                return Problem("Entity set 'BlogAppContext.Comments'  is null.");
            }
            var comment = await _context.Comments.FindAsync(id);
            if (comment != null)
            {
                _context.Comments.Remove(comment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommentExists(string id)
        {
            return (_context.Comments?.Any(e => e.CommentID == id)).GetValueOrDefault();
        }
    }
}

Controllers/PostsController.cs
using System;
using BlogApp.Data;
using BlogApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogApp.Services;

namespace BlogApp.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class PostsController : Controller
    {
        private readonly BlogAppContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly AzureStorge _storge;

        public PostsController(
            BlogAppContext context,
            IWebHostEnvironment webHostEnvironment,
            AzureStorge storge
        )
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _storge = storge;
        }

        private string SearchString = "";
        private string SelectedCategoryID = "";

        [AllowAnonymous]
        public async Task<IActionResult> Index(string searchString, string selectedCategoryID)
        {
            if (_context.Posts == null)
            {
                return Problem("Entity set database is null.");
            }

            SearchString = searchString;
            SelectedCategoryID = selectedCategoryID;

            IQueryable<Category> categorieQuery = from c in _context.Categories select c;

            var postQuery = from p in _context.Posts select p;
            postQuery.Include(p => p.Category).Include(p => p.BlogAppUser);

            if (!string.IsNullOrEmpty(searchString))
            {
                postQuery = postQuery.Where(
                    p => p.Title.ToLower().Contains(searchString.ToLower())
                );
            }
            if (!string.IsNullOrEmpty(selectedCategoryID))
            {
                postQuery = postQuery.Where(c => c.CategoryID == selectedCategoryID);
            }
            postQuery = postQuery.Where(p => p.IsPublished).Take(6);

            await GenerateCategoriesData();

            var viewModel = new PostViewModel
            {
                PostData = await postQuery.ToListAsync(),
                Categories = new SelectList(
                    await categorieQuery.Distinct().ToListAsync(),
                    "CategoryID",
                    "Name"
                )
            };
            return View(viewModel);
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetMorePosts(int pageNumber, int pageSize)
        {
            int skip = (pageNumber - 1) * pageSize;
            var postQuery = from p in _context.Posts select p;
            postQuery = postQuery.Include(p => p.BlogAppUser).Include(p => p.Category);

            if (!string.IsNullOrEmpty(SearchString))
            {
                postQuery = postQuery.Where(
                    p => p.Title.ToLower().Contains(SearchString.ToLower())
                );
            }
            if (!string.IsNullOrEmpty(SelectedCategoryID))
            {
                postQuery = postQuery.Where(c => c.CategoryID == SelectedCategoryID);
            }

            var posts = await postQuery.Skip(skip).Take(pageSize).ToListAsync();

            bool hasMorePosts = posts.Any() ? true : false;

            if (hasMorePosts)
            {
                return PartialView("_PostsPartial", posts);
            }
            else
            {
                return NotFound();
            }
        }

        private async Task GenerateCategoriesData()
        {
            var query = from c in _context.Categories select c;
            var categories = await query.ToListAsync();
            ViewData["CategoriesData"] = categories;
        }

        // GET: Manage
        public async Task<IActionResult> Manage()
        {
            var blogAppContext = _context.Posts
                .Include(p => p.BlogAppUser)
                .Include(p => p.Category);
            return View(await blogAppContext.ToListAsync());
        }

        // GET: Posts/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.BlogAppUser)
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.PostID == id);
            if (post == null)
            {
                return NotFound();
            }
            string[] postParagraphs = post.Content.Split(
                new[] { Environment.NewLine },
                StringSplitOptions.None
            );
            ViewBag.PostParagraphs = postParagraphs;

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            ViewData["BlogUserID"] = new SelectList(_context.Users, "Id", "UserName");
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "Name");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PostCreateViewModel post)
        {
            if (ModelState.IsValid)
            {
                Post data = new Post
                {
                    Title = post.Title,
                    Content = post.Content,
                    CategoryID = post.CategoryID,
                    BlogUserID = post.BlogUserID,
                    PublishedDate = GetVietameseTimeZone(),
                    IsPublished = post.IsPublished,
                    Introduction = post.Introduction,
                    ImgUrl = post.ImgUrl
                };

                if (post.Image != null && post.Image.Length != 0)
                {
                    // string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "imgs");
                    // Directory.CreateDirectory(uploadsFolder);

                    // string filePath = Path.Combine(uploadsFolder, post.Image.FileName);
                    // using (var stream = new FileStream(filePath, FileMode.Create))
                    // {
                    //     await post.Image.CopyToAsync(stream);
                    // }
                    // data.ImgUrl = post.Image.FileName;

                    string fileName = post.Image.FileName;
                    using (var stream = new MemoryStream())
                    {
                        await post.Image.CopyToAsync(stream);
                        string imageName = post.Image.FileName;
                        string imageUrl = await _storge.UploadImageAsync(stream, imageName);
                        data.ImgUrl = imageUrl;
                    }
                }
                _context.Add(data);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Manage));
            }
            ViewData["BlogUserID"] = new SelectList(
                _context.Users,
                "Id",
                "UserName",
                post.BlogUserID
            );
            ViewData["CategoryID"] = new SelectList(
                _context.Categories,
                "CategoryID",
                "Name",
                post.CategoryID
            );
            return View(post);
        }

        private void PopulateCategoriesDropDownList(object selectedCategory = null)
        {
            var categoriesQuery = from d in _context.Categories orderby d.Name select d;
            ViewBag.CategoryID = new SelectList(
                categoriesQuery.AsNoTracking(),
                "CategoryID",
                "Name",
                selectedCategory
            );
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var postData = await _context.Posts
                .AsNoTracking()
                .FirstOrDefaultAsync(p => p.PostID == id);

            if (postData == null)
            {
                return NotFound();
            }
            PostUpdateViewModel data = new PostUpdateViewModel
            {
                Title = postData.Title,
                Content = postData.Content,
                IsPublished = postData.IsPublished,
                CategoryID = postData.CategoryID,
                Introduction = postData.Introduction,
                ImgUrl = postData.ImgUrl
            };
            ViewBag.Img = postData.ImgUrl;
            PopulateCategoriesDropDownList(postData.CategoryID);
            return View(data);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, PostUpdateViewModel post)
        {
            if (id == null)
            {
                return NotFound();
            }

            var postToUpdate = await _context.Posts.FirstOrDefaultAsync(p => p.PostID == id);
            if (postToUpdate == null)
            {
                return NotFound();
            }
            postToUpdate.Title = post.Title;
            postToUpdate.Content = post.Content;
            postToUpdate.IsPublished = post.IsPublished;
            postToUpdate.LastUpdated = GetVietameseTimeZone();
            postToUpdate.CategoryID = post.CategoryID;
            postToUpdate.Introduction = post.Introduction;
            postToUpdate.ImgUrl = post.ImgUrl;

Views/Shared/_ButtonLoadMorePostPartial.cshtml
@if (@Model >= 6) {
    <div class="load-more">
        <input class="load-more-btn" type="submit" value="Load more Posts"/>
    </div>
}

Views/Shared/_ContactPartial.cshtml
 <div class="row align-item-center intro-container">
  <div class="col-md-8 intro align-self-center">
    <h1>Hey!, I'm Phuc Tuong</h1>
    <p>
      this is my personal blog writes about my life, coding, healthy,
      science...
    </p>
  </div>
  <div class="col-md-4 btn-intro align-self-center">
    <a asp-controller="Home" asp-action="Contact" type="button" class="btn-graper">
      <button class="rounded-pill btn-rounded">Get in touch <span><i class="fas fa-arrow-right"></i></span></button>
    </a>
  </div>
</div> 

Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wall'sBlog Dashboard</title>
    <link rel="icon" href="~/imgs/wallblog-icon.webp" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/web-font/css/all.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/web-font/js/all.min.js" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&family=Noto+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,400;1,500;1,600;1,700;1,800;1,900&family=Nunito:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Playfair:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Wall'Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Manage">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comments" asp-action="Index">Comments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="DownLoadDB">DownLoadDB</a>
                        </li>                        
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wall'sBlog</title>
    <link rel="icon" href="~/imgs/wallblog-icon.webp" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/web-font/css/all.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/web-font/js/all.min.js" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&family=Noto+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,400;1,500;1,600;1,700;1,800;1,900&family=Nunito:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Playfair:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&display=swap" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-expand-lg nav-bg navbar-dark shadow" id="nav-fixed-top">
      <div class="container">

        <button
        id="navbarToggler"
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbar"
        aria-controls="navbar"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
          <span class="open-icon"><i class="fa-solid fa-bars"></i></span>
          <span class="close-icon" style="display: none"
          ><i class="fa-solid fa-xmark"></i
        ></span>
        </button>

        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"
        >Wall'sBlog</a>

        <div class="navbar-custom collapse navbar-collapse justify-content-end" id="navbar">
          <ul class="navbar-nav">
             <li class="nav-item">
            <a
              class="nav-link text-light"
              asp-area=""
              asp-controller="Home"
              asp-action="Index"
              >HOME</a>
            </li>
           <li class="nav-item">
            <a
              class="nav-link text-light"
              asp-area=""
              asp-controller="Posts"
              asp-action="Index"
              >BLOGS</a>
          </li>
             <li class="nav-item">
            <a
              class="nav-link text-light"
              asp-area=""
              asp-controller="Home"
              asp-action="Portfolio"
              >PORTFOLIO</a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link text-light"
              asp-area=""
              asp-controller="Home"
              asp-action="Contact"
              >CONTACT</a>
          </li>
          </ul>
        </div>
      </div>
    </nav>
  
    <div class="container-fluid-lg body-padding">
      <main role="main">
          @RenderBody()
      </main>
    </div>   
 

  <footer class="border-top text-muted footer footer">
  <div class="container p-3 d-flex justify-content-center align-items-center">
    <div class="row">
      <div
        class="col-md-4 col-lg-4 contact-box"
      >
        <div class="contact-box__icon">
          <i class="fa-solid fa-square-phone"></i>
        </div>
        <div class="contact-box__info">
          <a href="#" class="contact-box__info--title">+84 378941261</a>
          <p class="contact-box__info--subtitle">Mon-Fri 9am-6pm (+7 GMT)</p>
        </div>
      </div>

      <div
        class="col-md-4 col-lg-4 contact-box"
      >
        <div class="contact-box__icon">
          <i class="fa-solid fa-envelope"></i>
        </div>
        <div class="contact-box__info">
          <a href="#" class="contact-box__info--title"
            >phuctuong0862@gmail.com</a
          >
          <p class="contact-box__info--subtitle">Online support</p>
        </div>
      </div>

      <div
        class="col-md-4 col-lg-4 contact-box"
      >
        <div class="contact-box__icon">
          <i class="fa-solid fa-map-location-dot"></i>
        </div>
        <div class="contact-box__info">
          <a href="#" class="contact-box__info--title">Can Tho, VN</a>
          <p class="contact-box__info--subtitle">9 CMT8, An Hoa, Ninh Kieu</p>
        </div>
      </div>
    </div>
  </div>

   <div class="container-fluid footer-sm p-3 d-flex justify-content-center align-items-center" style="background-color: #000000">
      <div class="row text-center text-light">
        <div class="col-md-6 mb-4 mb-md-0 text-nowrap pt-2 pb-2">
          Connect with me on social media
        </div>
        <div class="col-md-6 mb-md-0">
          <a href="https://www.facebook.com/tuong.huynhphuc.39?mibextid=ZbWKwL" target="_blank"><i class="fab fa-facebook"></i></a>
          <a href="https://github.com/WallHuynh" target="_blank"><i class="fab fa-github"></i></a>
          <a href="https://www.linkedin.com/in/tuong-huynh-phuc-60198a228" target="_blank"><i class="fab fa-linkedin"></i></a>
          <a href="https://instagram.com/wallhuynh_17?igshid=MzNlNGNkZWQ4Mg==" target="_blank"><i class="fab fa-instagram"></i></a>
        </div>
      </div>
    </div>

    <div class=" container-fluid footer-bottom pt-5 pb-5">
    <div class="container">
      <div class="row text-center text-white">
        <div class="col-12">
          <div class="footer-bottom__copyright">
            &COPY; Copyright 2023 <a asp-controller="Home" asp-action="Index">Wall'sBlog</a>
          </div>
        </div>
      </div>
    </div>
  </div>

</footer>

</body>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</html>

Views/Shared/_PortfolioLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wall'sBlog</title>
    <link rel="icon" href="~/imgs/wallblog-icon.webp" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/web-font/css/all.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/web-font/js/all.min.js" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&family=Noto+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,400;1,500;1,600;1,700;1,800;1,900&family=Nunito:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Playfair:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&display=swap" rel="stylesheet">
</head>
<body class="container portfolio-body">
    <main role="main">
          @RenderBody()
    </main>
</body>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</html>

Views/Shared/_PostNavbar.cshtml
@{
  string viewCategoryId =  (string)ViewContext.RouteData.Values["id"];
}

<div class="post-navbar" id="id-post-nav">
  <ul class="post-nav-list">
    <li id="posts" class="post-nav-item post-nav-item--active"><a asp-controller="Posts" asp-action="Index">All Posts</a></li>
    @foreach ( var category in (IEnumerable<Category>)Model)
    {
      <li id="@category.CategoryID" class="post-nav-item"><a asp-controller="Categories" asp-action="Details" asp-route-id="@category.CategoryID">@category.Name</a></li>
    }
  </ul>
</div>

 
<script>
  // Get all the navigation links
  const navLinks = document.querySelectorAll('.post-nav-item');
  const PostLink = document.querySelector('#default')
  // Add event listeners to each navigation link
  navLinks.forEach(link => {
      if ("@viewCategoryId" == link.id) {
        console.log('bing go')
        navLinks.forEach(navLink => navLink.classList.remove('post-nav-item--active'));
        link.classList.add('post-nav-item--active');
      }
  });
</script>

Views/Shared/_PostsPartial.cshtml
@model List<Post>

@foreach (var post in Model)
        {
            <div class="post-item">
                <a asp-controller="Posts" asp-action="Details" asp-route-id="@post.PostID">
                    <img src="@post.ImgUrl" width="100%" height="auto"/>
                </a>

                <a asp-controller="Categories" asp-action="Details" asp-route-id="@post.CategoryID" class="button-64"><span class="text">@post.Category?.Name</span></a>
                
                <a asp-controller="Posts" asp-action="Details" asp-route-id="@post.PostID">
                    <h5>@post.Title</h5>
                </a>
                <p>@post.Introduction</p>
            </div>
        }