Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace BlogApp.Models
{
    public class Category
    {
        [Key]
        public string CategoryID { get; set; }

        [StringLength(50)]
        public string Name { get; set; }

        [StringLength(200)]
        public string? Description { get; set; }
        public ICollection<Post> Posts { get; set; }
        public Category()
        {
            CategoryID = Guid.NewGuid().ToString();
        }
    }
}

Controllers/CategoriesController.cs
using BlogApp.Data;
using BlogApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogApp.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class CategoriesController : Controller
    {
        private readonly BlogAppContext _context;

        public CategoriesController(BlogAppContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return _context.Categories != null
                ? View(await _context.Categories.ToListAsync())
                : Problem("Entity set 'BlogAppContext.Categories'  is null.");
        }

        // GET: Categories/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var queryPost = from p in _context.Posts select p;
            queryPost = queryPost
                .Include(p => p.Category)
                .Include(p => p.BlogAppUser)
                .Where(p => p.CategoryID == id)
                .Where(p => p.IsPublished)
                .OrderByDescending(p => p.PublishedDate);

            var queryCategories = from c in _context.Categories select c;
            var categories = await queryCategories.ToListAsync();
            CategoryPostViewModel data = new CategoryPostViewModel
            {
                PostData = await queryPost.ToListAsync(),
                SelectedCategory = queryCategories.FirstOrDefault(c => c.CategoryID == id)
            };
            ViewData["CategoriesData"] = categories;

            return View(data);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatecategoryViewModel category)
        {
            if (ModelState.IsValid)
            {
                Category data = new Category
                {
                    Name = category.Name,
                    Description = category.Description
                };
                _context.Add(data);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            string id,
            [Bind("CategoryID,Name,Description")] Category category
        )
        {
            if (id != category.CategoryID)
            {
                return NotFound();
            }

            // if (ModelState.IsValid)
            // {
            try
            {
                _context.Update(category);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CategoryExists(category.CategoryID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
            // }
            // return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FirstOrDefaultAsync(m => m.CategoryID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'BlogAppContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(string id)
        {
            return (_context.Categories?.Any(e => e.CategoryID == id)).GetValueOrDefault();
        }
    }
}

Controllers/PostsController.cs
using System;
using BlogApp.Data;
using BlogApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogApp.Services;

namespace BlogApp.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class PostsController : Controller
    {
        private readonly BlogAppContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly AzureStorge _storge;

        public PostsController(
            BlogAppContext context,
            IWebHostEnvironment webHostEnvironment,
            AzureStorge storge
        )
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _storge = storge;
        }

        private string SearchString = "";
        private string SelectedCategoryID = "";

        [AllowAnonymous]
        public async Task<IActionResult> Index(string searchString, string selectedCategoryID)
        {
            if (_context.Posts == null)
            {
                return Problem("Entity set database is null.");
            }

            SearchString = searchString;
            SelectedCategoryID = selectedCategoryID;

            IQueryable<Category> categorieQuery = from c in _context.Categories select c;

            var postQuery = from p in _context.Posts select p;
            postQuery.Include(p => p.Category).Include(p => p.BlogAppUser);

            if (!string.IsNullOrEmpty(searchString))
            {
                postQuery = postQuery.Where(
                    p => p.Title.ToLower().Contains(searchString.ToLower())
                );
            }
            if (!string.IsNullOrEmpty(selectedCategoryID))
            {
                postQuery = postQuery.Where(c => c.CategoryID == selectedCategoryID);
            }
            postQuery = postQuery.Where(p => p.IsPublished).Take(6);

            await GenerateCategoriesData();

            var viewModel = new PostViewModel
            {
                PostData = await postQuery.ToListAsync(),
                Categories = new SelectList(
                    await categorieQuery.Distinct().ToListAsync(),
                    "CategoryID",
                    "Name"
                )
            };
            return View(viewModel);
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetMorePosts(int pageNumber, int pageSize)
        {
            int skip = (pageNumber - 1) * pageSize;
            var postQuery = from p in _context.Posts select p;
            postQuery = postQuery.Include(p => p.BlogAppUser).Include(p => p.Category);

            if (!string.IsNullOrEmpty(SearchString))
            {
                postQuery = postQuery.Where(
                    p => p.Title.ToLower().Contains(SearchString.ToLower())
                );
            }
            if (!string.IsNullOrEmpty(SelectedCategoryID))
            {
                postQuery = postQuery.Where(c => c.CategoryID == SelectedCategoryID);
            }

            var posts = await postQuery.Skip(skip).Take(pageSize).ToListAsync();

            bool hasMorePosts = posts.Any() ? true : false;

            if (hasMorePosts)
            {
                return PartialView("_PostsPartial", posts);
            }
            else
            {
                return NotFound();
            }
        }

        private async Task GenerateCategoriesData()
        {
            var query = from c in _context.Categories select c;
            var categories = await query.ToListAsync();
            ViewData["CategoriesData"] = categories;
        }

        // GET: Manage
        public async Task<IActionResult> Manage()
        {
            var blogAppContext = _context.Posts
                .Include(p => p.BlogAppUser)
                .Include(p => p.Category);
            return View(await blogAppContext.ToListAsync());
        }

        // GET: Posts/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.BlogAppUser)
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.PostID == id);
            if (post == null)
            {
                return NotFound();
            }
            string[] postParagraphs = post.Content.Split(
                new[] { Environment.NewLine },
                StringSplitOptions.None
            );
            ViewBag.PostParagraphs = postParagraphs;

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            ViewData["BlogUserID"] = new SelectList(_context.Users, "Id", "UserName");
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "Name");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PostCreateViewModel post)
        {
            if (ModelState.IsValid)
            {
                Post data = new Post
                {
                    Title = post.Title,
                    Content = post.Content,
                    CategoryID = post.CategoryID,
                    BlogUserID = post.BlogUserID,
                    PublishedDate = GetVietameseTimeZone(),
                    IsPublished = post.IsPublished,
                    Introduction = post.Introduction,
                    ImgUrl = post.ImgUrl
                };

                if (post.Image != null && post.Image.Length != 0)
                {
                    // string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "imgs");
                    // Directory.CreateDirectory(uploadsFolder);

                    // string filePath = Path.Combine(uploadsFolder, post.Image.FileName);
                    // using (var stream = new FileStream(filePath, FileMode.Create))
                    // {
                    //     await post.Image.CopyToAsync(stream);
                    // }
                    // data.ImgUrl = post.Image.FileName;

                    string fileName = post.Image.FileName;
                    using (var stream = new MemoryStream())
                    {
                        await post.Image.CopyToAsync(stream);
                        string imageName = post.Image.FileName;
                        string imageUrl = await _storge.UploadImageAsync(stream, imageName);
                        data.ImgUrl = imageUrl;
                    }
                }
                _context.Add(data);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Manage));
            }
            ViewData["BlogUserID"] = new SelectList(
                _context.Users,
                "Id",
                "UserName",
                post.BlogUserID
            );
            ViewData["CategoryID"] = new SelectList(
                _context.Categories,
                "CategoryID",
                "Name",
                post.CategoryID
            );
            return View(post);
        }

        private void PopulateCategoriesDropDownList(object selectedCategory = null)
        {
            var categoriesQuery = from d in _context.Categories orderby d.Name select d;
            ViewBag.CategoryID = new SelectList(
                categoriesQuery.AsNoTracking(),
                "CategoryID",
                "Name",
                selectedCategory
            );
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var postData = await _context.Posts
                .AsNoTracking()
                .FirstOrDefaultAsync(p => p.PostID == id);

            if (postData == null)
            {
                return NotFound();
            }
            PostUpdateViewModel data = new PostUpdateViewModel
            {
                Title = postData.Title,
                Content = postData.Content,
                IsPublished = postData.IsPublished,
                CategoryID = postData.CategoryID,
                Introduction = postData.Introduction,
                ImgUrl = postData.ImgUrl
            };
            ViewBag.Img = postData.ImgUrl;
            PopulateCategoriesDropDownList(postData.CategoryID);
            return View(data);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, PostUpdateViewModel post)
        {
            if (id == null)
            {
                return NotFound();
            }

            var postToUpdate = await _context.Posts.FirstOrDefaultAsync(p => p.PostID == id);
            if (postToUpdate == null)
            {
                return NotFound();
            }
            postToUpdate.Title = post.Title;
            postToUpdate.Content = post.Content;
            postToUpdate.IsPublished = post.IsPublished;
            postToUpdate.LastUpdated = GetVietameseTimeZone();
            postToUpdate.CategoryID = post.CategoryID;
            postToUpdate.Introduction = post.Introduction;
            postToUpdate.ImgUrl = post.ImgUrl;

Views/Categories/Create.cshtml
@model BlogApp.Models.CreatecategoryViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>Create</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Categories/Delete.cshtml
@model BlogApp.Models.Category

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CategoryID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Categories/Details.cshtml
@model BlogApp.Models.CategoryPostViewModel

@{
    ViewData["Title"] = "Details";
    var postCount = @Model.PostData.Count;
}

<partial name="_PostNavbar" for="@ViewData["CategoriesData"]"/>

<h1 class="category-name">Category: @Model.SelectedCategory.Name</h1>

<div class="post-container rounded overflow-hidden">
    @if (@postCount > 0)
    {
        @foreach (var item in Model.PostData)
        {
        <div class="post-item">
            <a asp-controller="Posts" asp-action="Details" asp-route-id="@item.PostID">
                <img src="@item.ImgUrl"/>
            </a>

            <a asp-controller="Categories" asp-action="Details" asp-route-id="@item.CategoryID" class="button-64"><span class="text">@item.Category.Name</span></a>
            
            <a asp-controller="Posts" asp-action="Details" asp-route-id="@item.PostID">
                <h5>@item.Title</h5>
            </a>
            
            <p>@item.Introduction</p>
        </div>
        }
    } else {
        <h2 class="post-not-found">No post found</h2>
    } 
</div>

<partial name="_ContactPartial"/>

Views/Categories/Edit.cshtml
@model BlogApp.Models.Category

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Categories/Index.cshtml
@model IEnumerable<BlogApp.Models.Category>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>Categories</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>
<div class="table-manage">
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a class="btn btn-success" asp-action="Edit" asp-route-id="@item.CategoryID">Edit</a> |
                <a class="btn btn-warning" asp-action="Details" asp-route-id="@item.CategoryID">Details</a> |
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.CategoryID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>